leverage_jay_demo_1/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using leverage_jay_demo_1.Models;

namespace leverage_jay_demo_1.Controllers
{
    public class VehiclesController : Controller
    {
        private Vehicle_dmDBContext db = new Vehicle_dmDBContext();


        // GET : Vehicles/ImageUpload/5

        public ActionResult ImageUpload(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle_dm vehicle_dm = db.Vehicle_dms.Find(id);
            if (vehicle_dm == null)
            {
                return HttpNotFound();
            }
            return View(vehicle_dm);
        }



        // GET: Vehicles
        public ActionResult Index()
        {
            return View(db.Vehicle_dms.ToList());
        }

        // GET: Vehicles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle_dm vehicle_dm = db.Vehicle_dms.Find(id);
            if (vehicle_dm == null)
            {
                return HttpNotFound();
            }
            return View(vehicle_dm);
        }

        
       
        // GET: Vehicles/Create
        public ActionResult Create()
        {
            return View();
        }



        // POST: Vehicles/Upload
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ImageUpload(HttpPostedFileBase file, Vehicle_dm vehicle_dm)
        {
                if (file != null && file.ContentLength > 0)
                    try
                    {
                        string path = Path.Combine(Server.MapPath("~/Images"), Path.GetFileName(vehicle_dm.Registration_Number+file.FileName));
                        file.SaveAs(path);
                        vehicle_dm.Image_Path = vehicle_dm.Registration_Number + file.FileName;
                        ViewBag.Message = "File uploaded successfully with the file name " + vehicle_dm.Image_Path;

                        //let me save the data object to the database now that the image path has been updated
                        db.Entry(vehicle_dm).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                else
                {
                    ViewBag.Message = "You have not specified a file.";
                }
            return View();  
        }




        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Registration_Number,Manufacturer,Vehicle_Model,Covered,Image_Path,ReleaseDate")] Vehicle_dm vehicle_dm, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var error = "file exists";
            }

            else
            {
                var error = "file does not exist";
            }            

            if (ModelState.IsValid)
            {
                
               
                //saving the model object to the database
                
                db.Vehicle_dms.Add(vehicle_dm);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vehicle_dm);
        }

        // GET: Vehicles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle_dm vehicle_dm = db.Vehicle_dms.Find(id);
            if (vehicle_dm == null)
            {
                return HttpNotFound();
            }
            return View(vehicle_dm);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Registration_Number,Manufacturer,Vehicle_Model,Covered,Image_Path,ReleaseDate")] Vehicle_dm vehicle_dm)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicle_dm).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vehicle_dm);
        }

        // GET: Vehicles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle_dm vehicle_dm = db.Vehicle_dms.Find(id);
            if (vehicle_dm == null)
            {
                return HttpNotFound();
            }
            return View(vehicle_dm);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicle_dm vehicle_dm = db.Vehicle_dms.Find(id);
            db.Vehicle_dms.Remove(vehicle_dm);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //function that will check for uniqueness of the Registration_Number property


        public JsonResult IsRegistration_NumberExists(string Registration_Number)
        {
            //now checking if Registration_Number mathes the Registration_Number specified in the parameter
            //to achieve this, I am going to use the ANY extension method

            return Json(!db.Vehicle_dms.Any(x => x.Registration_Number == Registration_Number) , JsonRequestBehavior.AllowGet);
        }

    }//end of class definition
}

leverage_jay_demo_1/Views/Vehicles/Create.cshtml
@model leverage_jay_demo_1.Models.Vehicle_dm

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehicle_dm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Registration_Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Registration_Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Registration_Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vehicle_Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vehicle_Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vehicle_Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Covered, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Covered)
                    @Html.ValidationMessageFor(model => model.Covered, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">


        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

leverage_jay_demo_1/Views/Vehicles/Delete.cshtml
@model leverage_jay_demo_1.Models.Vehicle_dm

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle_dm</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Registration_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Registration_Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehicle_Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehicle_Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Covered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Covered)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image_Path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

leverage_jay_demo_1/Views/Vehicles/Details.cshtml
@model leverage_jay_demo_1.Models.Vehicle_dm

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vehicle_dm</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Registration_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Registration_Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehicle_Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehicle_Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Covered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Covered)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image_Path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

</dl>
    <img src="@Url.Content("~/Images/" + Model.Image_Path)" alt="vehicle image will come here" />
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

leverage_jay_demo_1/Views/Vehicles/Edit.cshtml
@model leverage_jay_demo_1.Models.Vehicle_dm

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehicle_dm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Registration_Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Registration_Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Registration_Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vehicle_Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vehicle_Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vehicle_Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Covered, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Covered)
                    @Html.ValidationMessageFor(model => model.Covered, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image_Path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image_Path, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image_Path, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

leverage_jay_demo_1/Views/Vehicles/ImageUpload.cshtml
@model leverage_jay_demo_1.Models.Vehicle_dm

@{
    ViewBag.Title = "ImageUpload";
}

<h2>ImageUpload</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Registration_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Registration_Number)
        </dd>
    </dl>
</div>


@using (Html.BeginForm("ImageUpload", "Vehicles", Model ,FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <label for="file">Upload Image:</label>
    <input type="file" name="file" id="file" /><br><br>
    <input type="submit" value="Upload Image" />
    <br><br>
    @ViewBag.Message
}

<br />
<p>
        @Html.ActionLink("Back to List", "Index")
</p>

leverage_jay_demo_1/Views/Vehicles/Index.cshtml
@model IEnumerable<leverage_jay_demo_1.Models.Vehicle_dm>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Registration_Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vehicle_Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Covered)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image_Path)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Registration_Number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Manufacturer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Vehicle_Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Covered)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Image_Path)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseDate)
        </td>
        <td>
            @Html.ActionLink("Edit Vehicle", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Vehicle Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete  Vehicle", "Delete", new { id=item.ID }) |
            @Html.ActionLink("Upload Image", "ImageUpload", new { id=item.ID})
            
        </td>
    </tr>
}

</table>